### ISSUE TITLE
Add support for scrollwheel map option

### ISSUE THREAD

**Issue by lifeisfoo** [dylanfprice/angular-gm#76]
Useful for avoid mouse capture during page scroll.

**Comment by dylanfprice** [comment]
This is already supported. When you create a gm-map you can set a gm-map-options attribute. This can be any of the options in google.maps.MapOptions, since the object is just passed through to google maps.

Please see http://dylanfprice.github.io/angular-gm/1.0.0/docs/#/api/angulargm.directive:gmMap
