### ISSUE TITLE
Bower package not up to date

### ISSUE THREAD

**Issue by loganwedwards** [dylanfprice/angular-gm#81]
First, I love the integration of Circle shapes. Fits the bill nicely for what I need. I noticed that v1.0.1 is on Bower and that's what is listed on the repo's homepage. After finagling with trying to get Circles to work, I started digging through the source and noticed that the references to the Circle constructors and directives are nowhere to be found in the bower packaged version. Bower should be updated with the newest source to avoid confusion.

Thanks for a great library!

**Comment by dylanfprice** [comment]
I'm sorry if there was some confusion with the broken docs page--it is fixed and back up now. Version 1.0.1 doesn't include the circles shapes and if you look at the [1.0.1 docs](http://dylanfprice.github.io/angular-gm/1.0.1/docs/#/api) you will see they are not there. I double checked that what is up on bower is what I expect a 1.0.1 release to be.

I will look into releasing a 1.0.2 with the addition of circles since it sounds like you could use this feature.

**Comment by dylanfprice** [comment]
Ok I released 1.0.2 please let me know if you run into any problems!

**Comment by loganwedwards** [comment]
Solid. Already implemented in my project. Nice work!
