### ISSUE TITLE
using angular-gm with  MarkerClusterer

### ISSUE THREAD

**Issue by nicksche** [dylanfprice/angular-gm#87]
I want to use Google MarkerClusterer for grouping markers, but i can't get instance for map and marker .

Maybe you know some other way to realize grouping for markers ? 

Thanks,
Nick

**Comment by dylanfprice** [comment]
Hi Nick,

If you need a direct handle on the map, you can do so as outlined here
<http://dylanfprice.github.io/angular-gm/2.0.1/docs/#/api/angulargm.service:angulargmContainer>.
From there you can probably achieve what you want though it might be messy.

A cleaner approach would probably be to implement your own directive which
utilizes the angulargmMapController
<https://github.com/dylanfprice/angular-gm/blob/master/src/controllers/angulargmMapController.js>
and it's associated methods to manipulate the markers. For instance you can
call `controller.forEachElement('marker', myFn)` to put your markers into
different groups.

Hope that helps.

**Comment by rognstad** [comment]
I've been working on this a bit and have made some progress, but I'm having a problem when I have several sets of markers and only want to group one of them. Because of transclusion, I'm not sure how to find the correct scope ID for the set of markers I am interested in.

Here's a little demo: http://plnkr.co/edit/itJxTv?p=preview
